# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e207a9b134cafdaea0bd531bb97a33d744eaa52d3fb5a4f023da93cf9c41e246fb4206f1ed051671e92c12e8de9b05def5829977d0d4735f710ecf9d2774a87

test:
  secret_key_base: 6d21629ebb0de5f797c6de6c9ebab2a78536a5d74329af6871531af8687110410b1ef30dd18ccb43cea6a78b862e83ff6aa561dcb878e1ad5803f978e611e0db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
